# Generated by Django 3.0.3 on 2021-04-16 00:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24)),
                ('ans1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24)),
                ('ans2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24)),
                ('ans3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=24)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('using_count', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=10)),
                ('type', models.IntegerField(default=0)),
                ('answer1', models.IntegerField(default=0)),
                ('answer2', models.IntegerField(default=0)),
                ('answer3', models.IntegerField(default=0)),
            ],
        ),
    ]
